### ISSUE TITLE
Component.render() is static

### ISSUE THREAD

**Issue by mindplay-dk** [sweetpalma/gooact#12]
So I don't know if you've abandoned this already, but I'm still interested ;-)

To try to make more sense of the types involved, I've started porting it to Typescript.

I've been puzzled by the `Component.render` method, which is declared as `static`, gets called as an instance method [here](https://github.com/sweetpalma/gooact/blob/master/gooact.js#L92), [here](https://github.com/sweetpalma/gooact/blob/master/gooact.js#L107) and [here](https://github.com/sweetpalma/gooact/blob/master/gooact.js#L122).

I tried this in a console:

```js
class Foo {
  static blah() {
  	console.log('hey');
  }
}

Foo.blah();

(new Foo()).blah(); // blah is not a function
```

And it fails, as I expected.

It doesn't look like these were introduced by accident? The initial commit declared this as `static` and then proceeded to call it as an instance-method.

I can't make sense of it. Why would that work?

**Comment by sweetpalma** [comment]
Hello there,

Thanks for pointing it out - but you're missing one important detail here, there are two .render() methods in Component class:

- Static method, which encapsulates some basic render logic, like firing hooks, attaching to the DOM, storing instance link, etc.
- Instance method, which is absent in the Component class itself, but MUST be defined in the child classes in order to work - that's the point where final VDOM tree is returned.

Does it makes sense?

**Comment by mindplay-dk** [comment]
Ah, of course!

Yeah, that's where Typescript shines and Javascript gets confusing - I will declare this as `abstract` 😃👍

**Comment by sweetpalma** [comment]
You're absolutely right - currently I am working on a couple of TypeScript projects, and after getting back to the pure JavaScript I feel confused sometimes - like, where are my type declarations and method modifiers?

**Comment by mindplay-dk** [comment]
You're using Typescript too, that's cool - if you'd like to see what I've got so far, [here it is](https://github.com/mindplay-dk/gooact/tree/typescript). (I've got it in strict mode, so there's a lot of warnings still, while I'm trying to figure out how to type-hint this correctly...)
