### ISSUE TITLE
When i use class Component, it throws up error.

### ISSUE THREAD

**Issue by z2014** [sweetpalma/gooact#2]
sorry for bothering you on weekends!
when i use class component to build an app, 
it get an error "Class constructor Component cannot be invoked without 'new'",
 how to fix that? 
this is my [demo](https://github.com/z2014/Blog/tree/master/simple-react)

**Comment by sweetpalma** [comment]
Hello, no problem - that's a pleasure for me that my article get's translated to other languages 😊
I believe that issue was related to the way you were importing modules - so I made a fork and slightly rearranged package.json by adding zero-configuration webpack build - check this pull request for details and feel free to ask if you have any questions:
https://github.com/z2014/Blog/pull/14

**Comment by sweetpalma** [comment]
Well - I checked your repository, seems like it works fine. Closing now, get in touch if something goes wrong.
